# Replica of mongodb/node-mongodb-native .github/workflows/release_notes.yml
name: release_notes

on:
  issue_comment:
    types: [created]

permissions:
  contents: write
  pull-requests: write

jobs:
  release_notes:
    if: |
      github.event_name == 'issue_comment' &&
      github.event.issue.pull_request &&
      github.event.comment.body == 'run release_notes'
    runs-on: ubuntu-latest
    steps:
      - name: check if triggering_actor is allowed
        # NOTE: it will also change if someone re-runs an old job
        run: |
          if ! [[ "${{ github.triggering_actor }}" =~ ^(hackeronelucasfutures-web)$ ]]; then
            echo "Triggering actor '${{ github.triggering_actor }}' is not allowed."
            exit 1
          fi
          echo "Triggering actor '${{ github.triggering_actor }}' authorised."

      - uses: actions/checkout@v4
        with:
          ref: refs/pull/${{ github.event.issue.number }}/head

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: npm install
        run: npm install

      - name: Run release-notes helper scripts
        run: |
          node .github/scripts/pr_list.mjs
          node .github/scripts/highlights.mjs
          node .github/scripts/release_notes.mjs
        env:
          GITHUB_TOKEN: ${{ github.token }}
